airline/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/',include('flights.urls')),
    path('users/',include("users.urls"))
]

flights/urls.py
from django.urls import path
from . import views 
app_name="flights"
urlpatterns = [
   path('',views.index,name="index"),
   path('<int:abc_id>',views.flight,name="flight"),
   path('passenger/',views.passenger,name="passenger"),
   path('<int:flight_id/book',views.book,name="book")

]

users/urls.py
from django.urls import path 
from . import views 
urlpatterns = [
    path("",views.index,name="index"),
    path("login",views.login_view,name="login"),
    path("logout",views.logout_view,name="logout")

]

flights/models.py
from django.db import models

class Airpot(models.Model):
    code=models.CharField(max_length=3)
    city=models.CharField(max_length=20)
  
    def __str__(self):
        return f"({self.code},{self.city})"

class Flight(models.Model):
    origin=models.ForeignKey(Airpot,on_delete=models.CASCADE,related_name="depatures")
    destination=models.ForeignKey(Airpot,on_delete=models.CASCADE,related_name="arrivals")
    duration=models.IntegerField()

    def __str__(self):
        return f'({self.origin},{self.destination},{self.duration})'

class Passenger(models.Model):
    sex_choices=[
    ('M',"Male"),
    ("F","Female"),
    ("N","Neutral") ]
    First_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    age=models.PositiveIntegerField()
    sex=models.CharField(max_length=1,choices=sex_choices)
    flights=models.ManyToManyField(Flight,blank=True,related_name="abcdefght")


    def __str__(self):
        return f"({self.First_name},{self.age},{self.sex},{self.last_name},{self.flights})"
   
    

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.shortcuts import render
from .models import Flight,Passenger
from django.http import HttpResponseRedirect 
from django.urls import reverse 

def index(request):   #we have created this views to retreive data from models.py 
    flights=Flight.objects.all()
    context={"flights":flights}
    return render(request,"flights/index.html",context)
    #reuturn render(request,"flight/index.html",{"flight":Flight.objects.all()})  # we cal also use this 

def flight(request,abc_id): #we have created this views to go to specific id 
    flight=Flight.objects.get(pk=abc_id)   #here abc_id is flight_id 
    passengers=flight.abcdefght.all()
    context=({"passengers":passengers,"flight":flight})
    return render(request,'flights/flight.html',context)


def passenger(request):
    passenger=Passenger.objects.all()
    
    return render(request,'flights/passenger.html',{"passenger":passenger})

def book(request,flight_id):
    if request.method=='POST':
      flight=Flight.objects.get(pk=flight_id)
      passenger=Passenger.objects.get(pk=int(request.POST["passenger"]))
      passenger.flight.add(flight)
      return HttpResponseRedirect(reverse("flight" ,args=(flight.id)))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse 


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))

def login_view(request):
    return render(request,'users/login.html')

def logout_view(request):
    pass 

flights/templates/flights/flight.html
{% extends 'flights/layout.html' %}

{% block content %}
<style>
    .grid_container {
        display: grid;
        grid-template-rows: 100px 300px;
    }
</style>

<style>
    .fly {
        display: grid;
        grid-template-columns: 100px 200px 50px;
    }
</style>


<h1> Flight {{flight.id}} </h1>
<div class="grid_container">
    <div>
        <div class="fly">
            <div>flight origin <br> <br>{{flight.origin}}</div>
            <div>flight destination <br> <br> {{flight.destination}}</div>
            <div>flight duration <br> <br>{{flight.duration}}</pdiv>
            </div>
            <hr>
        </div>
        <div>
            <h1>passenger list </h1>
            <style>
                .per {
                    display: grid;
                    grid-template-columns: 100px 200px 50px 50px;
                }
            </style>
            <div class="per">

                <div>serial no <br> <br></div>
                <div>Name <br> <br></div>
                <div>Age <br> <br></div>
                <div>Sex <br> <br></div>


            </div>

            {% for person in passengers%}
            <div class="per">

                <div>{{person.id}}</div>
                <div>{{person.First_name}} {{person.last_name}}</div>
                <div>{{person.age}}</div>
                <div>{{person.sex}}</div>


            </div>
            <br>
            {% endfor %}
            
        </div>
        <a href="{% url 'flights:index' %}">Go back to flight section</a>
        <br>
    
    <br>    
    <form action="{% url 'flights:flight' flight.id  %}" method="POST">
        {% csrf_token %}
    <label >First Name 
        <input type="text", name="First Name ", placeholder="first name ">
       </label>
    
    <label>Last name
        <input type="text" , name="Last Name ", placeholder="last name "
    </label>
    <input type="submit" value="submit">
    </form>
    </div>
    
    
    {% endblock %}

flights/templates/flights/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flights information page </title>
</head>
<body>
   <h1>Flights</h1>
   <ol>
    {% for flight in flights %}
    <li><a href="{% url 'flights:flight' flight.id  %}"> Flight {{flight.id }} : {{ flight.origin}} to {{ flight.destination}} :  duration  {{flight.duration}}</a></li>
    <br>
   {% endfor %}
</ol> 

</body>
</html>

flights/templates/flights/layout.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
 </head>
 <body>
    {% block content %}

    {% endblock %}
 </body>
 </html>

flights/templates/flights/passenger.html
{% extends 'flights/layout.html' %}


{% block content %}
<style>
    .per{
        display: grid;
        grid-template-columns:100px 200px 50px 50px 200px ;
    }
    </style>
    <div class="per">

        <div>serial no <br> <br></div>
        <div>Name <br> <br></div>
        <div>Age <br> <br></div>
        <div>Sex <br> <br></div>
        <div>Flight <br> <br></div>
        
        </div>
    
{% for person in passenger %}
<div class="per">

    <div>{{person.id}}</div>
    <div>{{person.First_name}} {{person.last_name}}</div>
    <div>{{person.age}}</div>
    <div>{{person.sex}}</div>
    
    
</div>
<br>
{% endfor %}
{% endblock %}

users/templates/users/login.html
{% extends 'users/main.html' %}
{% block content %}






{% endblock %}

users/templates/users/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>